# Generated by Django 3.2.5 on 2024-03-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
